name: origin_novel
description: "起源小说"

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  # 国际化
  flutter_localizations:
    sdk: flutter
  isar: 4.0.0-dev.14
  isar_flutter_libs: 4.0.0-dev.14
  intl: ^0.19.0
  get: ^4.6.6
  logger: ^2.3.0
  flex_color_scheme: ^7.3.1
  cupertino_icons: ^1.0.8
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  path_provider: ^2.1.3
  dio: ^5.4.3+1
  dio_cookie_manager: ^3.1.1
  dio_cache_interceptor: ^3.5.0
  dio_smart_retry: ^6.0.0
  pretty_dio_logger: ^1.3.1
  cookie_jar: ^4.0.8
  connectivity_plus: ^6.0.3
  flutter_smart_dialog: ^4.9.7+7
  flutter_rust_bridge: 2.0.0-dev.37
  cached_network_image: ^3.3.1
  rust_lib_origin_novel:
    path: rust_builder

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.11
  freezed: ^2.5.2
  json_serializable: ^6.8.0




flutter:
  uses-material-design: true
  fonts:
    - family: AlibabaSans Nornal
      fonts:
        - asset: fonts/AlibabaSans Nornal/AlibabaSans-Black.otf
        - asset: fonts/AlibabaSans Nornal/AlibabaSans-Bold.otf
        - asset: fonts/AlibabaSans Nornal/AlibabaSans-Heavy.otf
        - asset: fonts/AlibabaSans Nornal/AlibabaSans-Light.otf
        - asset: fonts/AlibabaSans Nornal/AlibabaSans-Medium.otf
        - asset: fonts/AlibabaSans Nornal/AlibabaSans-Regular.otf
    - family: AlibabaSans Nornal ltalics
      fonts:
        - asset: fonts/AlibabaSans Nornal ltalics/AlibabaSans-BoldItalic.otf
        - asset: fonts/AlibabaSans Nornal ltalics/AlibabaSans-HeavyItalic.otf
        - asset: fonts/AlibabaSans Nornal ltalics/AlibabaSans-Italic.otf
        - asset: fonts/AlibabaSans Nornal ltalics/AlibabaSans-LightItalic.otf
        - asset: fonts/AlibabaSans Nornal ltalics/AlibabaSans-MediumItalic.otf
    - family: 阿里巴巴普惠体
      fonts:
        - asset: fonts/阿里巴巴普惠体/Alibaba-PuHuiTi-Bold.ttf
        - asset: fonts/阿里巴巴普惠体/Alibaba-PuHuiTi-Heavy.ttf
        - asset: fonts/阿里巴巴普惠体/Alibaba-PuHuiTi-Light.ttf
        - asset: fonts/阿里巴巴普惠体/Alibaba-PuHuiTi-Medium.ttf
        - asset: fonts/阿里巴巴普惠体/Alibaba-PuHuiTi-Regular.ttf
  assets:
    - assets/image/default/
    - assets/
    - assets/image/
    - assets/test/
    - assets/test/image/
    - assets/test/content/





flutter_intl:
  enabled: true
  class_name: S
  main_locale: zh
  arb_dir: lib/app/l10n
  output_dir: lib/app/l10n/generated